[package]
name = "rust-swiftclient"
version = "0.1.0"
authors = ["Joel Wright <joel.wright@gmail.com>"]

[dependencies]
docopt = ">=0.6"
hyper = ">=0.8.0"
chrono = ">=0.2"
rustc-serialize = ">=0.3.19"
url = ">=0.2"

# [dependencies.chrono]
# version = "*"
# features = ["rustc-serialize"]
